### ISSUE TITLE
Changes to user docs

### ISSUE THREAD

**Issue by nmassey001** [cedadev/nlds-client#8]
From Matt Pritchard:

Great Job 
[@neil.massey](https://ncas-talk.slack.com/team/U2LK2FZ51)
 
[@jack.leland](https://ncas-talk.slack.com/team/U02B9M6FH9D)
 Some comments below:

1.  [Introduction to the NLDS] Could it be better to refer to the functional role of the object store, i.e. “cache”, rather than call it object store? The fact that it’s object store is less important to users. I’d suggest changing 1st sentence to “The Near-Line Data Store (NLDS) is a multi-tiered storage solution that uses Object Storage as a front end cache to a tape library.” and then replace all references to Object Store/age to cache from then on, apart from where you say about belonging to the OS tenancy. (However, see my comment #3a]
2. [Introduction to the NLDS] “with a common interface to all.” -> “such that the user only needs to interact with the service itself rather than moving moves data between disk and cache.”  (I assume that’s still true?)
3. [Setting up the NLDS Client]
    a. [architecture question] I hadn’t actually realised that the cache was effectively divided into Object Storage tenancies: I had thought the NLDS cache was just 1 big lump of storage transparent to the user. Is that still an option, or would that cause permissions problems for different groups? Given that those same data in the cache are now read/writable via other S3 clients while there, does that cause a problem? What if they’re modified or deleted after having been put in the cache but before they’re written to tape? Likewise for retrieval? Are they “locked” in any way? Apologies if these are already-solved design problems.
    b. I think bullets 2 & 3 need merging: If I belong to a group workspace, then in NLDS-world**, I shouldn’t care about the distinction between disk and tape in terms of access control (**I know they’ve been different in ET/JDMA-world, but I think this is our chance to end that)
    c. “However, all of the fields in the server section of the file, and the authentication section will need to be provided by the JASMIN system adminstrators.” We should point to a page in the help docs (or somewhere else we agree) which shows current values for these.
4.  [Running the NLDS client for the first time]
   a. “user name” -> “username”: (and all subsequent instances)
   b. “[loginx.jasmin.ac.uk](http://loginx.jasmin.ac.uk/)” -> replace with link [login servers](https://help.jasmin.ac.uk/article/191-login-servers) i.e. the docs page decribing/listing the current set of them. loginx looks a bit too much like an actual host name.
5.  [Copying a single file (PUT) to the NLDS]
    a. “transaction_id” should be in inline code markup
    b. Bristol Zoo is now closed, sadly! https://www.itv.com/news/westcountry/2022-12-09/report-claims-bristol-zoo-put-money-before-people-to-sell-off-prized-asset
6.  The rest looks great, I look forward to testing it, so will try and have a go asap.

**Comment by jackleland** [comment]
Addressed as of #14
